/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --config wrangler.v2.jsonc` (hash: 3341a5e9a17b8aab5c9a5637b7867fe7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/light-index");
	}
	interface Env {
		VibecoderStore: KVNamespace;
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		CUSTOM_DOMAIN: "vibesdk-v2.elbaan.workers.dev";
		CONTROL_PLANE_URL: "http://localhost:8080";
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY: string;
		CLOUDFLARE_AI_GATEWAY_URL: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		WORKFLOWS: Workflow<Parameters<import("./worker/light-index").VibeWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "CUSTOM_DOMAIN" | "CONTROL_PLANE_URL" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY" | "CLOUDFLARE_AI_GATEWAY_URL" | "CLOUDFLARE_AI_GATEWAY_TOKEN">> {}
}
